plugin:
    code: Fvera.SeoTweaker
    name: fvera.seotweaker::lang.plugin.name
    description: fvera.seotweaker::lang.plugin.description
    author: Fernando Vera
    icon: icon-ambulance
    homepage: https://github.com/Fvera/october-seo-tweaker
